trigger: none
pool: self hosted

stages:
  - stage: Linting
    displayName: Linting_stage
    jobs:
      - job: Linting_job
        displayName: Lintingjob
        steps:
        - task: PowerShell@2
          displayName: Run_marksdown 
          inputs:
            targetType: 'inline'
            script: |
              npm install -g markdownlint-cli      
              markdownlint $(System.DefaultWorkingDirectory)/
        - task: PowerShell@2
          displayName: Run_yamllint
          continueOnError: true
          inputs:
             targetType: 'inline'
             script: |
              pip install --user yamllint
              yamllint $(System.DefaultWorkingDirectory)/
        - task: PowerShell@2
          displayName: Run_CSSlint(Stylelint)
          continueOnError: true
          inputs:
             targetType: 'inline'
             script: |
              npm install --save-dev stylelint stylelint-config-standard
               stylelint "src/**/*.css" --config stylelint.config.mjs




  - stage: Build
    displayName: Build_Stage
    jobs:
      - job: Build_Job
        displayName: npm_install
        steps:
        - task: NodeTool@0
          displayName: Install Node.js
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'

        - task: PowerShell@2
          displayName: Install Dependencies
          inputs:
            targetType: 'inline'
            script: 'npm install'

        - task: PowerShell@2
          displayName: Build the Project
          inputs:
            targetType: 'inline'
            script: 'npm run build'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/build'
            artifact: 'todo_Frontend'
            publishLocation: 'pipeline'