trigger: none
pool: self hosted

stages:
  - stage: Build
    displayName: Build_Stage
    jobs:
      - job: Build_Job
        displayName: npm_install
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'winget install OpenJS.NodeJS.LTS'

    
